apiVersion: v1
kind: Service
metadata:
  # 代表的是我们的smartbook本体
  name: smartbook
  # 说明书
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app: smartbook
  ports:
    - name: http
      protocol: TCP
      port: 81
      targetPort: 8082
